[package]
name = "gloweygraph"
version = "0.0.1"
description = "A library for drawing glowey graphs"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
keywords = ["graph", "glow", "glowey", "render", "draw"]
license = "BSD-2-Clause"

[dependencies]
glium = "13.3"
