[package]
name = "glowygraph"
version = "0.5.1"
description = "A library for drawing glowy graphs"
documentation = "https://vadixidav.github.io/glowygraph/glowygraph/"
repository = "https://github.com/vadixidav/glowygraph"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
keywords = ["graph", "glow", "glowy", "render", "draw"]
license = "Unlicense"

[dependencies]
glium = "0.14.0"
num = "0.1.32"
nalgebra = "0.5.1"
rand = "0.3.14"
