[package]
name = "glowygraph"
version = "0.1.1"
description = "A library for drawing glowy graphs"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
keywords = ["graph", "glow", "glowy", "render", "draw"]
license = "BSD-2-Clause"

[dependencies]
glium = "0.13.3"
petgraph = "0.2.2"
num = "0.1.30"
nalgebra = "0.5.1"
